### ISSUE TITLE
HTML Tag not working

### ISSUE THREAD

**Issue by Vostro162** [sahandnayebaziz/Hypertext#22]
I guess i found a bug.
if i have this line code 
```swift
let html = body { div {	b {"Hello World"}	} }.render()
```
this is working but if i have this line code
```swift
let html = html { body { b {"Hello World"}	} }.render()
```
is not any more working

**Comment by sahandnayebaziz** [comment]
Hi @Vostro162, this is happening because these two names are conflicting:

````swift
let html = html { body { b {"Hello World"}	} }.render()
      ^      ^
````

There are two easy ways to fix this! The first way is to explicitly name Hypertext in the second use of `html` so that the compiler can keep the two separate, like so:
````swift
import Hypertext

let html = Hypertext.html { body { b {"Hello World"}	} }.render()
````

The second way is to change the name of the first `html` to something different so you can keep it short, like so:
````swift
import Hypertext

let htmlString = html { body { b {"Hello World"}	} }.render()
````

😄

**Comment by Vostro162** [comment]
Ohh Shit i thought this was my misstake sorry for the issue post and thx for the help

**Comment by sahandnayebaziz** [comment]
You're welcome :)
